[package]
name = "lexa"
version = "0.1.0"
authors = ["Hermes Zhang <zhangchenhui2006@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
